<script setup lang="ts">
/**
 * EditorCoverArea — 封面预览组件
 *
 * 显示在标题区域上方，自动根据文章内容生成封面。
 * 实时预览：正文改变时封面自动更新（防抖）。
 * 点击可替换为自定义图片。
 */
import { ref, watch, onBeforeUnmount } from 'vue'
import { generateTextCover } from '@/lib/utils/generateTextCover'
import type { BlogPost } from '@/components/logic/api'

const props = defineProps<{
  title: string
  introduction?: string
  paragraphs?: Array<{ content: string }>
  tags: string[]
}>()

const emit = defineEmits<{
  'update:coverUrl': [url: string]
}>()

const coverUrl = ref('')
const isCustomCover = ref(false) // true = 用户手动上传，不再自动更新

/** 是否有封面 */
const hasCover = ref(false)
/** 是否自动生成的封面（区别于用户手动上传） */
const isAutoGenerated = ref(false)

// 防抖生成封面
let debounceTimer: ReturnType<typeof setTimeout> | null = null

function generateCover() {
  if (isCustomCover.value || !props.title) return

  const post = {
    id: 'preview',
    slug: '',
    title: props.title || 'Untitled',
    introduction: props.introduction || '',
    paragraphs: (props.paragraphs ?? []).map((p) => ({
      content: p.content,
      type: 'text' as const,
      pid: '',
      word_count: 0
    })),
    tags: props.tags
  } as BlogPost

  try {
    coverUrl.value = generateTextCover(post, true)
    hasCover.value = true
    isAutoGenerated.value = true
    emit('update:coverUrl', coverUrl.value)
  } catch {
    // canvas 可能不可用
  }
}

function scheduleGenerate() {
  if (isCustomCover.value) return
  if (debounceTimer) clearTimeout(debounceTimer)
  debounceTimer = setTimeout(generateCover, 500)
}

watch(() => props.title, scheduleGenerate)
watch(() => props.introduction, scheduleGenerate)
watch(() => props.tags, scheduleGenerate)

// 初始生成
scheduleGenerate()

onBeforeUnmount(() => {
  if (debounceTimer) clearTimeout(debounceTimer)
})

/** 用户点击替换封面 */
function handleReplace() {
  const input = document.createElement('input')
  input.type = 'file'
  input.accept = 'image/*'
  input.onchange = () => {
    const file = input.files?.[0]
    if (!file) return
    if (!file.type.startsWith('image/')) return
    if (file.size > 10 * 1024 * 1024) return

    const blobUrl = URL.createObjectURL(file)
    coverUrl.value = blobUrl
    isCustomCover.value = true
    isAutoGenerated.value = false
    hasCover.value = true
    emit('update:coverUrl', blobUrl)
  }
  input.click()
}
</script>

<template>
  <!-- 有封面 → 预览 -->
  <div v-if="hasCover" class="cover-area" @click="handleReplace">
    <img :src="coverUrl" alt="封面预览" class="cover-image" />
    <div class="cover-overlay">
      <span>点击替换封面</span>
    </div>
    <div v-if="isAutoGenerated" class="cover-badge">
      封面已自动生成，可正常使用 · 不满意可点击替换
    </div>
  </div>
  <!-- 无封面（标题为空等原因未自动生成）→ 上传入口 -->
  <div v-else class="cover-area cover-area--empty" @click="handleReplace">
    <div class="cover-placeholder">
      <svg
        width="28"
        height="28"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
        <circle cx="8.5" cy="8.5" r="1.5" />
        <polyline points="21 15 16 10 5 21" />
      </svg>
      <span>点击上传封面图片</span>
      <span class="cover-placeholder__hint">或等待填写标题后自动生成</span>
    </div>
  </div>
</template>

<style scoped>
.cover-area {
  position: relative;
  width: 100%;
  border-radius: var(--radius-lg);
  overflow: hidden;
  cursor: pointer;
  margin-bottom: var(--spacing-md);
  aspect-ratio: 640 / 400;
  max-height: 320px;
}

.cover-image {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}

.cover-overlay {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  background: rgba(0, 0, 0, 0);
  color: #fff;
  font-size: 14px;
  font-family: var(--font-sans);
  transition: background var(--transition-fast);
  opacity: 0;
}

.cover-area:hover .cover-overlay {
  background: rgba(0, 0, 0, 0.4);
  opacity: 1;
}

.cover-badge {
  position: absolute;
  bottom: 12px;
  left: 50%;
  transform: translateX(-50%);
  background: rgba(0, 0, 0, 0.65);
  color: #fff;
  font-size: 12px;
  font-family: var(--font-sans);
  padding: 4px 14px;
  border-radius: 20px;
  white-space: nowrap;
  pointer-events: none;
  backdrop-filter: blur(4px);
}

/* ─── 空封面占位 ─── */

.cover-area--empty {
  border: 2px dashed var(--border-color);
  background: var(--surface-hover-color, rgba(128, 128, 128, 0.03));
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition:
    border-color var(--transition-fast),
    background var(--transition-fast);
}

.cover-area--empty:hover {
  border-color: var(--primary-color);
  background: rgba(128, 128, 128, 0.06);
}

.cover-placeholder {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 6px;
  color: var(--text-tertiary);
  font-size: 14px;
  font-family: var(--font-sans);
}

.cover-placeholder__hint {
  font-size: 12px;
  color: var(--text-quaternary, rgba(128, 128, 128, 0.5));
}
</style>
