"""initial

Revision ID: 15b29d45b36c
Revises:
Create Date: 2026-06-15 16:14:55.157039
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from backend.plugins.cloud_integration.models import ArrayAsJSON, JSON, UUIDString
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.

revision: str = "15b29d45b36c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_index",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("asset_type", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column("tags", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("sid", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("asset_index", schema=None) as batch_op:
        batch_op.create_index(
            "ix_asset_index_owner_type", ["owner_id", "asset_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_asset_index_sid"), ["sid"], unique=True)
        batch_op.create_index(
            "ix_asset_index_source", ["asset_type", "source_id"], unique=True
        )

    op.create_table(
        "blog_comments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("paragraph_pid", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("sid", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("blog_comments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_blog_comments_sid"), ["sid"], unique=True)

    op.create_table(
        "blog_favorites",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("sid", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("post_id", "user_id", name="uq_blog_favorites_post_user"),
    )
    with op.batch_alter_table("blog_favorites", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_blog_favorites_sid"), ["sid"], unique=True)

    op.create_table(
        "blog_likes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("sid", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("post_id", "user_id", name="uq_blog_likes_post_user"),
    )
    with op.batch_alter_table("blog_likes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_blog_likes_sid"), ["sid"], unique=True)

    op.create_table(
        "blog_paragraphs",
        sa.Column("pid", sa.String(length=64), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("heading", sa.String(length=256), nullable=True),
        sa.Column("media_url", sa.String(length=1024), nullable=True),
        sa.Column("caption", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("sid", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("pid"),
    )
    with op.batch_alter_table("blog_paragraphs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_blog_paragraphs_post_id"), ["post_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_blog_paragraphs_sid"), ["sid"], unique=True
        )

    op.create_table(
        "blog_post_files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("oss_file_id", sa.UUID(), nullable=False),
        sa.Column("file_index", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("sid", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("blog_post_files", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_blog_post_files_post_id"), ["post_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_blog_post_files_sid"), ["sid"], unique=True
        )

    op.create_table(
        "blog_post_tags",
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("post_id", "tag_id"),
    )
    op.create_table(
        "blog_posts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("slug", sa.String(length=256), nullable=False),
        sa.Column("cover_url", sa.String(length=1024), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column("required_level", sa.Integer(), nullable=False),
        sa.Column("subtitles", sa.JSON(), nullable=True),
        sa.Column("introduction", sa.Text(), nullable=True),
        sa.Column("paragraph_ids", sa.JSON(), nullable=True),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("category_id", sa.String(length=32), nullable=True),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.Column("comment_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sid", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    with op.batch_alter_table("blog_posts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_blog_posts_sid"), ["sid"], unique=True)

    op.create_table(
        "blog_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("reporter_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("sid", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("blog_reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_blog_reports_sid"), ["sid"], unique=True)

    op.create_table(
        "blog_tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("color", sa.String(length=8), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("sid", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("blog_tags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_blog_tags_sid"), ["sid"], unique=True)

    op.create_table(
        "change_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.String(length=64), nullable=False),
        sa.Column("operator_id", sa.UUID(), nullable=False),
        sa.Column("operation", sa.String(length=32), nullable=False),
        sa.Column("changes", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("sid", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("change_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_change_logs_sid"), ["sid"], unique=True)

    op.create_table(
        "code_repos",
        sa.Column("id", UUIDString(length=36), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("git_url", sa.String(length=1024), nullable=False),
        sa.Column(
            "git_branch", sa.String(length=256), server_default="main", nullable=False
        ),
        sa.Column("git_token", sa.String(length=512), nullable=True),
        sa.Column("created_by", UUIDString(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("sid", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("code_repos", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_code_repos_sid"), ["sid"], unique=True)

    op.create_table(
        "config_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "group", sa.String(length=64), server_default="general", nullable=False
        ),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("is_sensitive", sa.Boolean(), server_default="false", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("config_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_config_entries_group"), ["group"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_config_entries_key"), ["key"], unique=True)

    op.create_table(
        "crawl_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("content_type", sa.String(length=64), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=256), nullable=True),
        sa.Column(
            "crawled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("file_path", sa.String(length=1024), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("sid", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("crawl_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_crawl_records_sid"), ["sid"], unique=True)

    op.create_table(
        "datasets",
        sa.Column("id", UUIDString(length=36), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("file_count", sa.Integer(), nullable=False),
        sa.Column("tags", ArrayAsJSON(), nullable=True),
        sa.Column("config", JSON(), nullable=True),
        sa.Column("created_by", UUIDString(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("sid", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("datasets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_datasets_sid"), ["sid"], unique=True)

    op.create_table(
        "login_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=False),
        sa.Column("device_name", sa.String(length=128), nullable=True),
        sa.Column("location", sa.String(length=128), nullable=True),
        sa.Column(
            "login_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("login_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_login_history_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "moderation_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.String(length=64), nullable=False),
        sa.Column("submitter_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sid", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("moderation_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_moderation_records_sid"), ["sid"], unique=True
        )

    op.create_table(
        "monitor_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("components", sa.JSON(), nullable=False),
        sa.Column("refresh_interval", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("sid", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("monitor_templates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_monitor_templates_sid"), ["sid"], unique=True
        )

    op.create_table(
        "nickname_blacklist",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("keyword", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=256), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("keyword"),
    )
    op.create_table(
        "oss_files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.String(length=64), nullable=True),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=True),
        sa.Column("storage_type", sa.String(length=32), nullable=False),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_accessed",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("sid", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("oss_files", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_oss_files_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_oss_files_owner_id"), ["owner_id"], unique=False
        )
        batch_op.create_index(
            "ix_oss_files_owner_storage", ["owner_id", "storage_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_oss_files_sid"), ["sid"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_oss_files_storage_type"), ["storage_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_oss_files_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "page_component_permissions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("page_name", sa.String(length=128), nullable=False),
        sa.Column("component_name", sa.String(length=128), nullable=False),
        sa.Column("visible", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "level", "page_name", "component_name", name="uq_level_page_component"
        ),
    )
    with op.batch_alter_table("page_component_permissions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_page_component_permissions_level"), ["level"], unique=False
        )

    op.create_table(
        "training_jobs",
        sa.Column("id", UUIDString(length=36), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("creator_id", UUIDString(length=36), nullable=False),
        sa.Column("model_config", JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("logs_path", sa.String(length=512), nullable=True),
        sa.Column("result_path", sa.String(length=512), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("gpu_hours", sa.Float(), nullable=False),
        sa.Column("total_cost", sa.Float(), nullable=False),
        sa.Column("artifacts", JSON(), nullable=True),
        sa.Column("artifact_verified", sa.Integer(), nullable=False),
        sa.Column("repo_url", sa.String(length=1024), nullable=True),
        sa.Column(
            "repo_branch", sa.String(length=256), server_default="main", nullable=True
        ),
        sa.Column("repo_token", sa.String(length=512), nullable=True),
        sa.Column("dataset_config", JSON(), nullable=True),
        sa.Column("training_script", sa.String(length=512), nullable=True),
        sa.Column("log_file_path", sa.String(length=512), nullable=True),
        sa.Column(
            "log_pattern",
            sa.String(length=256),
            server_default="epoch\\s+(\\d+).*?loss\\s*[:=]\\s*([\\d.]+)",
            nullable=True,
        ),
        sa.Column(
            "requirements_file",
            sa.String(length=512),
            server_default="requirements.txt",
            nullable=True,
        ),
        sa.Column("progress_info", JSON(), nullable=True),
        sa.Column(
            "orchestrator_step",
            sa.String(length=64),
            server_default="idle",
            nullable=True,
        ),
        sa.Column("orchestrator_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sid", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("training_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_training_jobs_sid"), ["sid"], unique=True)

    op.create_table(
        "user_known_devices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("device_name", sa.String(length=128), nullable=False),
        sa.Column("device_mac", sa.String(length=64), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_known_devices", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_known_devices_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "user_oss_quotas",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("quota_bytes", sa.BigInteger(), nullable=False),
        sa.Column("speed_multiplier", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_oss_quotas", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_oss_quotas_user_id"), ["user_id"], unique=True
        )

    op.create_table(
        "user_previous_names",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_previous_names", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_previous_names_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("default_post_permission", sa.String(length=16), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("theme", sa.String(length=16), nullable=False),
        sa.Column("notify_comment_reply", sa.Boolean(), nullable=False),
        sa.Column("notify_like", sa.Boolean(), nullable=False),
        sa.Column("notify_system", sa.Boolean(), nullable=False),
        sa.Column("privacy_show_online", sa.Boolean(), nullable=False),
        sa.Column("privacy_show_login_history", sa.Boolean(), nullable=False),
        sa.Column("privacy_show_badges", sa.Boolean(), nullable=False),
        sa.Column("default_post_status", sa.String(length=16), nullable=False),
        sa.Column("auto_save_interval", sa.Integer(), nullable=False),
        sa.Column("extras", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "user_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("device_name", sa.String(length=128), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("sid", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_tokens_sid"), ["sid"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_user_tokens_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "user_violations",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("violation_type", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("ban_duration", sa.Integer(), nullable=False),
        sa.Column(
            "banned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("unbanned_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_violations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_violations_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=128), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("nickname", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("avatar", sa.String(length=1024), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("links", sa.JSON(), nullable=True),
        sa.Column("badges", sa.JSON(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("blog_quality_level", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "deletion_status",
            sa.String(length=32),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column("deletion_reason", sa.String(length=32), nullable=True),
        sa.Column("deletion_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("login_count", sa.Integer(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_ip", sa.String(length=64), nullable=True),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("sid", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index("ix_users_created_at", ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_sid"), ["sid"], unique=True)

    op.create_table(
        "artifacts",
        sa.Column("id", UUIDString(length=36), nullable=False),
        sa.Column("job_id", UUIDString(length=36), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("artifact_type", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("storage_location", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("sid", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["training_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_artifacts_sid"), ["sid"], unique=True)

    op.create_table(
        "training_instances",
        sa.Column("id", UUIDString(length=36), nullable=False),
        sa.Column("job_id", UUIDString(length=36), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("provider_instance_id", sa.String(length=256), nullable=True),
        sa.Column("instance_name", sa.String(length=256), nullable=False),
        sa.Column("gpu_type", sa.String(length=64), nullable=False),
        sa.Column("gpu_count", sa.Integer(), nullable=False),
        sa.Column("ssh_host", sa.String(length=256), nullable=True),
        sa.Column("ssh_port", sa.Integer(), nullable=False),
        sa.Column("ssh_user", sa.String(length=128), nullable=True),
        sa.Column("ssh_key_path", sa.String(length=512), nullable=True),
        sa.Column("ssh_password", sa.String(length=256), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("last_heartbeat", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stopped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sid", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["training_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("training_instances", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_training_instances_sid"), ["sid"], unique=True
        )

    op.create_table(
        "training_task_steps",
        sa.Column("id", UUIDString(length=36), nullable=False),
        sa.Column("job_id", UUIDString(length=36), nullable=False),
        sa.Column("step_name", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("result_data", JSON(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("sid", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["training_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("training_task_steps", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_training_task_steps_sid"), ["sid"], unique=True
        )

    op.create_table(
        "training_costs",
        sa.Column("id", UUIDString(length=36), nullable=False),
        sa.Column("job_id", UUIDString(length=36), nullable=False),
        sa.Column("instance_id", UUIDString(length=36), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("gpu_type", sa.String(length=64), nullable=False),
        sa.Column("hourly_rate", sa.Float(), nullable=False),
        sa.Column("duration_hours", sa.Float(), nullable=False),
        sa.Column("total_cost", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("sid", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["training_instances.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["training_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("training_costs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_training_costs_sid"), ["sid"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("training_costs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_training_costs_sid"))

    op.drop_table("training_costs")
    with op.batch_alter_table("training_task_steps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_training_task_steps_sid"))

    op.drop_table("training_task_steps")
    with op.batch_alter_table("training_instances", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_training_instances_sid"))

    op.drop_table("training_instances")
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artifacts_sid"))

    op.drop_table("artifacts")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_sid"))
        batch_op.drop_index("ix_users_created_at")

    op.drop_table("users")
    with op.batch_alter_table("user_violations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_violations_user_id"))

    op.drop_table("user_violations")
    with op.batch_alter_table("user_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_tokens_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_tokens_sid"))

    op.drop_table("user_tokens")
    op.drop_table("user_settings")
    with op.batch_alter_table("user_previous_names", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_previous_names_user_id"))

    op.drop_table("user_previous_names")
    with op.batch_alter_table("user_oss_quotas", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_oss_quotas_user_id"))

    op.drop_table("user_oss_quotas")
    with op.batch_alter_table("user_known_devices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_known_devices_user_id"))

    op.drop_table("user_known_devices")
    with op.batch_alter_table("training_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_training_jobs_sid"))

    op.drop_table("training_jobs")
    with op.batch_alter_table("page_component_permissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_page_component_permissions_level"))

    op.drop_table("page_component_permissions")
    with op.batch_alter_table("oss_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_oss_files_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_oss_files_storage_type"))
        batch_op.drop_index(batch_op.f("ix_oss_files_sid"))
        batch_op.drop_index("ix_oss_files_owner_storage")
        batch_op.drop_index(batch_op.f("ix_oss_files_owner_id"))
        batch_op.drop_index(batch_op.f("ix_oss_files_created_at"))

    op.drop_table("oss_files")
    op.drop_table("nickname_blacklist")
    with op.batch_alter_table("monitor_templates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_monitor_templates_sid"))

    op.drop_table("monitor_templates")
    with op.batch_alter_table("moderation_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_moderation_records_sid"))

    op.drop_table("moderation_records")
    with op.batch_alter_table("login_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_login_history_user_id"))

    op.drop_table("login_history")
    with op.batch_alter_table("datasets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_datasets_sid"))

    op.drop_table("datasets")
    with op.batch_alter_table("crawl_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_crawl_records_sid"))

    op.drop_table("crawl_records")
    with op.batch_alter_table("config_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_config_entries_key"))
        batch_op.drop_index(batch_op.f("ix_config_entries_group"))

    op.drop_table("config_entries")
    with op.batch_alter_table("code_repos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_code_repos_sid"))

    op.drop_table("code_repos")
    with op.batch_alter_table("change_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_change_logs_sid"))

    op.drop_table("change_logs")
    with op.batch_alter_table("blog_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_blog_tags_sid"))

    op.drop_table("blog_tags")
    with op.batch_alter_table("blog_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_blog_reports_sid"))

    op.drop_table("blog_reports")
    with op.batch_alter_table("blog_posts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_blog_posts_sid"))

    op.drop_table("blog_posts")
    op.drop_table("blog_post_tags")
    with op.batch_alter_table("blog_post_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_blog_post_files_sid"))
        batch_op.drop_index(batch_op.f("ix_blog_post_files_post_id"))

    op.drop_table("blog_post_files")
    with op.batch_alter_table("blog_paragraphs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_blog_paragraphs_sid"))
        batch_op.drop_index(batch_op.f("ix_blog_paragraphs_post_id"))

    op.drop_table("blog_paragraphs")
    with op.batch_alter_table("blog_likes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_blog_likes_sid"))

    op.drop_table("blog_likes")
    with op.batch_alter_table("blog_favorites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_blog_favorites_sid"))

    op.drop_table("blog_favorites")
    with op.batch_alter_table("blog_comments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_blog_comments_sid"))

    op.drop_table("blog_comments")
    with op.batch_alter_table("asset_index", schema=None) as batch_op:
        batch_op.drop_index("ix_asset_index_source")
        batch_op.drop_index(batch_op.f("ix_asset_index_sid"))
        batch_op.drop_index("ix_asset_index_owner_type")

    op.drop_table("asset_index")
    # ### end Alembic commands ###
