name: CI - PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "docs/**"
      - "*.md"
  workflow_dispatch:

jobs:
  check-lint:
    uses: ./.github/workflows/check-lint.yml

  check-security:
    uses: ./.github/workflows/check-security.yml
    permissions:
      actions: read
      contents: read
      security-events: write

  test-unit:
    uses: ./.github/workflows/test-unit.yml

  test-integration:
    uses: ./.github/workflows/test-integration.yml

  test-e2e:
    uses: ./.github/workflows/test-e2e.yml
    with:
      browsers: '["chromium"]'
    continue-on-error: true
